// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdfGhfXlwP1GoZ_AONOFsD7ftnIHO2WE',
    appId: '1:301401989275:android:7f7b86e0b73d6967bda63e',
    messagingSenderId: '301401989275',
    projectId: 'uteeth-3pi-puc',
    storageBucket: 'uteeth-3pi-puc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg9rz2YvhKlP6WZ6Ptj6-tjfci1NiVRtY',
    appId: '1:301401989275:ios:f578c567bbc1e915bda63e',
    messagingSenderId: '301401989275',
    projectId: 'uteeth-3pi-puc',
    storageBucket: 'uteeth-3pi-puc.appspot.com',
    iosClientId: '301401989275-l5dpj3c00thqje5nscgtt1e6ph03f1t8.apps.googleusercontent.com',
    iosBundleId: 'br.com.puccampinas.uteeth3pi.uteethSocorrista',
  );
}
